version: "3.9"

services:
  localstack:
    networks:
      - ls_network
    container_name: localstack
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway

    environment:
      - DEBUG=1  # enable more verbose logs
      - DOCKER_HOST=unix:///var/run/docker.sock #unix socket to communicate with the docker daemon
      - LOCALSTACK_HOST=localstack # where services are available from other containers
      - LAMBDA_DOCKER_NETWORK=ls_network
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60
      - ENFORCE_IAM=0

    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./init-resources.sh:/etc/localstack/init/ready.d/init-resources.sh"
      - "./first-step.jar:/etc/localstack/init/ready.d/first-step.jar"


networks:
  ls_network:
    name: ls_network
